The following modules were not unloaded:
  (Use "module --force purge" to unload all):

  1) xalt/2.10.45

Inactive Modules:
  1) xalt


Currently Loaded Modules:
  1) gmp/6.2.1    4) zlib/1.2.11      7) openmpi/4.0.6
  2) mpfr/3.1.6   5) gcc/8.4.1        8) cuda/11.2.2
  3) mpc/1.1.0    6) numactl/2.0.14   9) modtree/gpu

Inactive Modules:
  1) xalt

 

/home/x-cli32/chaohan/anaconda3/envs/trl_env/lib/python3.9/site-packages/transformers/utils/hub.py:111: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/trl-lib/tldr/resolve/main/README.md
Retrying in 1s [Retry 1/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/trl-lib/tldr/resolve/main/README.md
Retrying in 2s [Retry 2/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/trl-lib/tldr/resolve/main/README.md
Retrying in 4s [Retry 3/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/trl-lib/tldr/resolve/main/README.md
Retrying in 8s [Retry 4/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/trl-lib/tldr/resolve/main/README.md
Retrying in 8s [Retry 5/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/trl-lib/tldr/resolve/main/README.md
Using the latest cached version of the dataset since trl-lib/tldr couldn't be found on the Hugging Face Hub
Found the latest cached dataset configuration 'default' at /home/x-cli32/chaohan/huggingface/datasets/trl-lib___tldr/default/0.0.0/21233da376667088e6eb1ce4ce19ed832c2935d3 (last modified on Mon Jul 14 12:18:47 2025).
Traceback (most recent call last):
  File "/anvil/scratch/x-cli32/projects/trl/test_grpo.py", line 13, in <module>
    training_args = GRPOConfig(output_dir="Qwen2-0.5B-GRPO")
  File "<string>", line 176, in __init__
  File "/anvil/scratch/x-cli32/projects/trl/trl/trainer/grpo_config.py", line 559, in __post_init__
    super().__post_init__()
  File "/home/x-cli32/chaohan/anaconda3/envs/trl_env/lib/python3.9/site-packages/transformers/training_args.py", line 1726, in __post_init__
    raise ValueError(error_message)
ValueError: Your setup doesn't support bf16/gpu.
